name: Docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'changeset-release/**'
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}
jobs:
  build:
    if: |
      github.repository == 'reuters-graphics/paparazzo' &&
      ((github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch')
    permissions:
      contents: write
      pull-requests: write
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Repo
        uses: actions/checkout@v4

      - id: setup
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - id: install
        name: Install dependencies
        run: npm ci

      - id: docs
        name: Build docs
        run: npm run build:docs

      - id: commit
        name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Build docs"
          git push
